// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"github.com/mrpsousa/api/internal/entity"
	"github.com/mrpsousa/api/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// TransactionInterface is an autogenerated mock type for the TransactionInterface type
type TransactionInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: transaction
func (_m *TransactionInterface) Create(transaction *entity.Transaction) error {
	ret := _m.Called(transaction)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Transaction) error); ok {
		r0 = rf(*transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAssociateBalance provides a mock function with given fields:
func (_m *TransactionInterface) GetAssociateBalance() ([]dto.DtoSellers, error) {
	ret := _m.Called()

	var r0 []dto.DtoSellers
	if rf, ok := ret.Get(0).(func() []dto.DtoSellers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DtoSellers)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductorBalance provides a mock function with given fields:
func (_m *TransactionInterface) GetProductorBalance() ([]dto.DtoSellers, error) {
	ret := _m.Called()

	var r0 []dto.DtoSellers
	if rf, ok := ret.Get(0).(func() []dto.DtoSellers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DtoSellers)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetForeignCourses provides a mock function with given fields:
func (_m *TransactionInterface) GetForeignCourses() ([]dto.DtoCourses, error) {
	ret := _m.Called()

	var r0 []dto.DtoCourses
	if rf, ok := ret.Get(0).(func() []dto.DtoCourses); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DtoCourses)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
