
name: CI-CD

on:
  push:
    branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: DockerHub Authentication
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Run tests
        run: go test -v ./...
      - name : Docker Image Building
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            mrpsousa/api-go-hubla:v${{github.run_number}}
            mrpsousa/api-go-hubla:latest
  CD:
      runs-on: ubuntu-latest
      needs: [CI]
      steps:
        - uses: actions/checkout@v3.5.2
        - name: Definition of Context 
          uses: Azure/k8s-set-context@v3.0
          with:
            method: kubeconfig
            kubeconfig: ${{secrets.K8S_CONFIG}}
        - name: Deploy to Kubernetes cluster
          uses: Azure/k8s-deploy@v4.9
          with: 
            images: mrpsousa/api-go-hubla:v${{github.run_number}}
            manifests: |
              k8s/deployment.yaml
